demoapp/urls.py
from django.urls import path

from . import views

app_name = "demoapp"
urlpatterns = [
    path("", views.ContactIndex.as_view(), name="contact-index"),
    path("list/", views.ContactList.as_view(), name="contact-list"),
    path("create/", views.create_contact, name="contact-create"),
    path("delete/<int:pk>/", views.delete_contact, name="contact-delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("demoapp.urls")),
]

demoapp/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=200)

    def __str__(self):
        return self.name

demoapp/views.py
from django.http import HttpResponseNotAllowed, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django import forms
from django.urls import reverse_lazy
from django.views import generic

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        model = Contact
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "phone_number": forms.TextInput(attrs={"class": "form-control"}),
        }


class ContactIndex(generic.TemplateView):
    template_name = "demoapp/contact_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = Contact.objects.all()
        context["form"] = ContactForm
        return context


def create_contact(request):
    if not request.method == "POST":
        raise HttpResponseNotAllowed
    form = ContactForm(request.POST)
    if form.is_valid():
        form.save()
        return render(request, "demoapp/contact_list.html", {"object_list": Contact.objects.all()})
    raise HttpResponseBadRequest


def delete_contact(request, pk):
    # remove the contact from list.
    Contact.objects.filter(pk=pk).delete()
    return render(request, "demoapp/contact_list.html", {"object_list": Contact.objects.all()})


class ContactList(generic.ListView):
    model = Contact

demoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Application</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
</head>
<body>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'; //insert csrf token when performing AJAX request
    })
    </script>
</body>
</html>

demoapp/templates/demoapp/contact_form.html
{% extends 'base.html' %}

{% block content %}

<div class="align-center col-10 offset-1">
    <div class="d-flex justify-content-between align-items-center">
        <p class="lead ml-0">My contacts</p>
        <form hx-post="{% url 'demoapp:contact-create' %}" hx-target='#contact-list' class="d-flex align-items-center" method="POST">
            {% csrf_token %}
{#            {{ form.as_p }}#}
            <input type="text" name="name" class="form-control-sm mr-2" placeholder="Enter name" hx-post="/check-name/" hx-trigger="keyup" hx-target="#name-exist"/>

            <input type="text" name="phone_number" class="form-control-sm mr-2" placeholder="Enter phone number" />

            <button hx-post='{% url "demoapp:contact-create"%}' hx-target='#contact-list' type="submit" class="btn btn-success btn-sm">Save</button>
        </form>
    </div>
    <hr/>

    <div id="contact-list">
        {% include 'demoapp/contact_list.html' %}
    </div>
</div>
{% endblock content %}

demoapp/templates/demoapp/contact_list.html
{% if object_list %}
{% csrf_token %}
<ul class="list-group col-4">
{% for contact in object_list %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ contact.name }}: {{ contact.phone_number }}
        <span class="badge badge-danger badge-pill" 
            style="cursor: pointer;"
            hx-delete="{% url 'demoapp:contact-delete' contact.pk %}"
            hx-target="#contact-list"
            hx-confirm="Are you sure you wish to delete?"
        >X</span>
    </li>
{% endfor %}
</ul>
{% else %}
<p>No Contact</p>
{% endif %}